// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8EAHNFm4m7JRHN-6x8_MGTE8T1X_RkCM',
    appId: '1:313295516572:web:981b64a1e04531284d8e59',
    messagingSenderId: '313295516572',
    projectId: 'theratyp-6e334',
    authDomain: 'theratyp-6e334.firebaseapp.com',
    storageBucket: 'theratyp-6e334.appspot.com',
    measurementId: 'G-B3K2YM4VJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvgi_tLpXwLYEEkDBJbKe4uXjIdYIji04',
    appId: '1:313295516572:android:2e9f0b912657a0d94d8e59',
    messagingSenderId: '313295516572',
    projectId: 'theratyp-6e334',
    storageBucket: 'theratyp-6e334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlbH8cxHr-AKmKUmQVB95CJELugm-myKM',
    appId: '1:313295516572:ios:b5e7167e1dd4fdc84d8e59',
    messagingSenderId: '313295516572',
    projectId: 'theratyp-6e334',
    storageBucket: 'theratyp-6e334.appspot.com',
    androidClientId: '313295516572-f7pjkuci3v2l4iml59s4c651cvikpeoa.apps.googleusercontent.com',
    iosClientId: '313295516572-d7j68kfhtpgf3s2fu4vr5jlk9qhh58v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.theratyp',
  );
}
